export interface TestTypeConfig {
  label: string;
  shortLabel: string;
  description: string;
  icon: string;
  hex: string;
  dotHex: string;
  softBg: string;          // e.g. "rgba(124,58,237,0.06)"
  gradient: string;        // CSS gradient string
  gradientFrom: string;
  gradientTo: string;
  // Tailwind classes (kept for backwards compat)
  color: string;
  textColor: string;
  bgColor: string;
  borderColor: string;
  // Copy
  emptyStateCopy: string;
  emptyStateAction: string;
  exampleName: string;
  exampleHypothesis: string;
  primaryConcept: string;
}

export const TEST_TYPE_THEME: Record<string, TestTypeConfig> = {
  CONTENT_TEST: {
    label: "Content Test",
    shortLabel: "Content",
    description: "A/B test storefront copy, images, and layout changes",
    icon: "✦",
    hex: "#7c3aed",
    dotHex: "#8b5cf6",
    softBg: "rgba(124,58,237,0.06)",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #6d28d9 100%)",
    gradientFrom: "#7c3aed",
    gradientTo: "#6d28d9",
    color: "bg-violet-500",
    textColor: "text-violet-700",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-100",
    emptyStateCopy: "Test headlines, hero images, CTAs, and layout changes without touching your theme code.",
    emptyStateAction: "Create content test",
    exampleName: "Hero Value Proposition Test",
    exampleHypothesis: "Changing the hero headline to emphasize fast shipping will increase add-to-cart rate by 10%.",
    primaryConcept: "DOM modifications",
  },
  SPLIT_URL: {
    label: "Split URL Test",
    shortLabel: "Split URL",
    description: "Redirect visitors between different URLs and measure conversion impact",
    icon: "⇄",
    hex: "#0284c7",
    dotHex: "#0ea5e9",
    softBg: "rgba(2,132,199,0.06)",
    gradient: "linear-gradient(135deg, #0284c7 0%, #0369a1 100%)",
    gradientFrom: "#0284c7",
    gradientTo: "#0369a1",
    color: "bg-sky-500",
    textColor: "text-sky-700",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-100",
    emptyStateCopy: "Route a percentage of visitors to an alternate URL and measure the landing page conversion impact.",
    emptyStateAction: "Create split URL test",
    exampleName: "Landing Page Layout Test",
    exampleHypothesis: "Sending paid traffic to the long-form landing page will increase conversion rate compared to the standard PDP.",
    primaryConcept: "URL routing",
  },
  OFFER_TEST: {
    label: "Offer Test",
    shortLabel: "Offers",
    description: "A/B test cart offers, free shipping thresholds, and incentives",
    icon: "◈",
    hex: "#059669",
    dotHex: "#10b981",
    softBg: "rgba(5,150,105,0.06)",
    gradient: "linear-gradient(135deg, #059669 0%, #047857 100%)",
    gradientFrom: "#059669",
    gradientTo: "#047857",
    color: "bg-emerald-600",
    textColor: "text-emerald-700",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-100",
    emptyStateCopy: "Test free shipping thresholds, free gifts, volume discounts, and cart incentives.",
    emptyStateAction: "Create offer test",
    exampleName: "Free Gift Threshold Test",
    exampleHypothesis: "Offering a free gift above $80 will increase AOV and revenue per visitor.",
    primaryConcept: "Cart incentives",
  },
  CHECKOUT_TEST: {
    label: "Checkout Test",
    shortLabel: "Checkout",
    description: "A/B test checkout blocks, trust badges, and messaging",
    icon: "▣",
    hex: "#4f46e5",
    dotHex: "#6366f1",
    softBg: "rgba(79,70,229,0.06)",
    gradient: "linear-gradient(135deg, #4f46e5 0%, #4338ca 100%)",
    gradientFrom: "#4f46e5",
    gradientTo: "#4338ca",
    color: "bg-indigo-600",
    textColor: "text-indigo-700",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-100",
    emptyStateCopy: "Test trust badges, payment icons, urgency messages, and custom content inside Shopify checkout.",
    emptyStateAction: "Create checkout test",
    exampleName: "Checkout Trust Badge Test",
    exampleHypothesis: "Adding payment security badges above the payment step will increase checkout completion rate.",
    primaryConcept: "Checkout UI blocks",
  },
  PRICE_TEST: {
    label: "Price Test",
    shortLabel: "Pricing+",
    description: "High-risk A/B test product prices with rollout and rollback",
    icon: "◎",
    hex: "#e11d48",
    dotHex: "#f43f5e",
    softBg: "rgba(225,29,72,0.06)",
    gradient: "linear-gradient(135deg, #e11d48 0%, #be123c 100%)",
    gradientFrom: "#e11d48",
    gradientTo: "#be123c",
    color: "bg-rose-600",
    textColor: "text-rose-700",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-100",
    emptyStateCopy: "Test product pricing with display-only or Shopify Function enforcement. Includes rollout, rollback, and margin impact analysis.",
    emptyStateAction: "Create price test",
    exampleName: "Premium Price Sensitivity Test",
    exampleHypothesis: "Increasing the hero product price by 8% will improve gross profit per visitor without materially reducing conversion rate.",
    primaryConcept: "Price matrix",
  },
  DISCOUNT_TEST: {
    label: "Discount Test",
    shortLabel: "Discounts",
    description: "A/B test discount mechanics and perceived value",
    icon: "⊖",
    hex: "#d97706",
    dotHex: "#f59e0b",
    softBg: "rgba(217,119,6,0.06)",
    gradient: "linear-gradient(135deg, #d97706 0%, #b45309 100%)",
    gradientFrom: "#d97706",
    gradientTo: "#b45309",
    color: "bg-amber-500",
    textColor: "text-amber-700",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-100",
    emptyStateCopy: "Test percentage vs fixed discounts, BXGY offers, and volume pricing to find what drives the most revenue.",
    emptyStateAction: "Create discount test",
    exampleName: "10% vs $15 Discount Test",
    exampleHypothesis: "A fixed $15 discount will create higher perceived value than 10% off, increasing conversion without hurting revenue per visitor.",
    primaryConcept: "Discount rules engine",
  },
  SHIPPING_TEST: {
    label: "Shipping Test",
    shortLabel: "Shipping+",
    description: "A/B test free shipping thresholds and delivery method presentation",
    icon: "◷",
    hex: "#0891b2",
    dotHex: "#06b6d4",
    softBg: "rgba(8,145,178,0.06)",
    gradient: "linear-gradient(135deg, #0891b2 0%, #0e7490 100%)",
    gradientFrom: "#0891b2",
    gradientTo: "#0e7490",
    color: "bg-cyan-600",
    textColor: "text-cyan-700",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-100",
    emptyStateCopy: "Optimize free shipping thresholds, hide/rename delivery methods, and add progress bars to increase AOV.",
    emptyStateAction: "Create shipping test",
    exampleName: "Free Shipping Threshold Test",
    exampleHypothesis: "Lowering the free shipping threshold from $75 to $50 will increase checkout completion without reducing profit per visitor.",
    primaryConcept: "Shipping strategy",
  },
  PERSONALIZATION_TEST: {
    label: "Personalization",
    shortLabel: "Personalization",
    description: "Targeted experiences for specific visitor segments — no A/B split",
    icon: "◉",
    hex: "#c026d3",
    dotHex: "#d946ef",
    softBg: "rgba(192,38,211,0.06)",
    gradient: "linear-gradient(135deg, #c026d3 0%, #a21caf 100%)",
    gradientFrom: "#c026d3",
    gradientTo: "#a21caf",
    color: "bg-fuchsia-600",
    textColor: "text-fuchsia-700",
    bgColor: "bg-fuchsia-50",
    borderColor: "border-fuchsia-100",
    emptyStateCopy: "Show targeted offers, content, and checkout experiences to specific audience segments without running an A/B test.",
    emptyStateAction: "Create personalization",
    exampleName: "Returning Visitor Offer",
    exampleHypothesis: "Showing returning visitors a cart-specific incentive will increase purchase completion rate.",
    primaryConcept: "Audience targeting",
  },
  TEMPLATE_TEST: {
    label: "Template Test",
    shortLabel: "Template",
    description: "Test Shopify theme templates — coming soon",
    icon: "⊞",
    hex: "#64748b",
    dotHex: "#94a3b8",
    softBg: "rgba(100,116,139,0.06)",
    gradient: "linear-gradient(135deg, #64748b 0%, #475569 100%)",
    gradientFrom: "#64748b",
    gradientTo: "#475569",
    color: "bg-slate-500",
    textColor: "text-slate-600",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
    emptyStateCopy: "Template tests are coming soon.",
    emptyStateAction: "Join waitlist",
    exampleName: "Template Test",
    exampleHypothesis: "",
    primaryConcept: "Theme templates",
  },
  THEME_TEST: {
    label: "Theme Test",
    shortLabel: "Theme",
    description: "A/B test entire Shopify themes — coming soon",
    icon: "◫",
    hex: "#71717a",
    dotHex: "#a1a1aa",
    softBg: "rgba(113,113,122,0.06)",
    gradient: "linear-gradient(135deg, #71717a 0%, #52525b 100%)",
    gradientFrom: "#71717a",
    gradientTo: "#52525b",
    color: "bg-zinc-500",
    textColor: "text-zinc-600",
    bgColor: "bg-zinc-50",
    borderColor: "border-zinc-200",
    emptyStateCopy: "Theme tests are coming soon.",
    emptyStateAction: "Join waitlist",
    exampleName: "Theme Test",
    exampleHypothesis: "",
    primaryConcept: "Full theme",
  },
};

export function getTestTypeTheme(type: string): TestTypeConfig {
  return TEST_TYPE_THEME[type] ?? {
    label: type,
    shortLabel: type,
    description: "",
    icon: "○",
    hex: "#64748b",
    dotHex: "#94a3b8",
    softBg: "rgba(100,116,139,0.06)",
    gradient: "linear-gradient(135deg, #64748b 0%, #475569 100%)",
    gradientFrom: "#64748b",
    gradientTo: "#475569",
    color: "bg-neutral-400",
    textColor: "text-neutral-600",
    bgColor: "bg-neutral-100",
    borderColor: "border-neutral-200",
    emptyStateCopy: "",
    emptyStateAction: "Create test",
    exampleName: "",
    exampleHypothesis: "",
    primaryConcept: "",
  };
}
