api_version = "2025-04"

[[extensions]]
name = "MarginLab Delivery Customization"
handle = "marginlab-delivery-customization"
uid = "27d252ec-d65c-b53d-1ff2-85ff760111c06a561515"
type = "function"
function_type = "delivery_customization"
